Feature/sbachmei/add social distancing folder
ihmeuw/covid-shared pull request #57
Opened 2020-11-19 23:43 UTC by stevebachmeier

2020-11-19 23:55 UTC, JosephWagner requested changes
I think you want to have this PR point at develop. Then we can have separate pr from develop to master for a new release. Notice how there are a bunch of other commits as part of this PR from other people?

Otherwise lgtm

2020-11-19 23:57 UTC, kathrynline requested changes
I would PR into develop instead of master, but your individual commit looks good to me.

2020-11-19 23:57 UTC, kathrynline commented on src/covid_shared/paths.py
>  MASK_USE_OUTPUT_ROOT = Path('/ihme/covid-19/mask-use-outputs')
Are we sure these deletions aren't going to impact any other users? I'd leave these folders for now.

2020-11-20 00:00 UTC, collijk approved these changes

2020-11-20 00:00 UTC, merged